spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: moviesApiSameer
      servlet:
        multipart:
          enable : true
          max-file-size: 10MB
          max-request-size: 10MB
project:
  poster: poster/
  base :
    url : "http://localhost:8080"

